### ISSUE TITLE
属性変更武器の追加が行えない

### ISSUE THREAD

**Issue by hoshimi** [hoshimi/motocal#31]
https://twitter.com/torisu_le/status/822794376023711744

**Comment by gin0606** [comment]
```
content.js:54108 Uncaught ReferenceError: elementTypes is not defined
    at Constructor.clickedConsiderNumber (http://hsimyu.net/motocal/build/content.js:54108:34)
    at Object.invokeGuardedCallback (http://hsimyu.net/motocal/build/content.js:37788:12)
    at executeDispatch (http://hsimyu.net/motocal/build/content.js:29619:21)
    at Object.executeDispatchesInOrder (http://hsimyu.net/motocal/build/content.js:29639:7)
    at executeDispatchesAndRelease (http://hsimyu.net/motocal/build/content.js:29076:22)
    at executeDispatchesAndReleaseTopLevel (http://hsimyu.net/motocal/build/content.js:29087:10)
    at Array.forEach (native)
    at forEachAccumulated (http://hsimyu.net/motocal/build/content.js:44260:9)
    at Object.processEventQueue (http://hsimyu.net/motocal/build/content.js:29261:7)
    at runEventQueueInBatch (http://hsimyu.net/motocal/build/content.js:37857:18)
    at Object.handleTopLevel [as _handleTopLevel] (http://hsimyu.net/motocal/build/content.js:37868:5)
    at handleTopLevelImpl (http://hsimyu.net/motocal/build/content.js:37946:24)
    at ReactDefaultBatchingStrategyTransaction.perform (http://hsimyu.net/motocal/build/content.js:43518:20)
    at Object.batchedUpdates (http://hsimyu.net/motocal/build/content.js:37052:19)
    at Object.batchedUpdates (http://hsimyu.net/motocal/build/content.js:41229:20)
    at dispatchEvent (http://hsimyu.net/motocal/build/content.js:38023:20)
clickedConsiderNumber @ content.js:54108
invokeGuardedCallback @ content.js:37788
executeDispatch @ content.js:29619
executeDispatchesInOrder @ content.js:29639
executeDispatchesAndRelease @ content.js:29076
executeDispatchesAndReleaseTopLevel @ content.js:29087
forEachAccumulated @ content.js:44260
processEventQueue @ content.js:29261
runEventQueueInBatch @ content.js:37857
handleTopLevel @ content.js:37868
handleTopLevelImpl @ content.js:37946
perform @ content.js:43518
batchedUpdates @ content.js:37052
batchedUpdates @ content.js:41229
dispatchEvent @ content.js:38023
```

再現したので一応ログ 📋

**Comment by hoshimi** [comment]
直しました
